version: '2'
services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - "5000"
    depends_on:
      - redis
      - lb
  redis:
    image: redis:alpine
#Probar con un ngnix
  lb:
    image: nginx
    volumes:
     - ./proxy.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always