version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - "3000"
  redis:
    image: redis:alpine
#Probar con un ngnix
  # lb:
  #   image: eeacms/haproxy
  #   depends_on:
  #     - web
  #   ports:
  #     - "80:3000"
  #     - "1936:1936"
  #   environment:
  #     BACKENDS: "web"
  #     DNS_ENABLED: "true"
  #     LOG_LEVEL: "info"  