version: '3'
services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/code
  redis:
    image: redis
  lb:
    image: tutum/haproxy
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=5000
      - BALANCE=roundrobin